SELECT ID, (SELECT FISH_NAME FROM FISH_NAME_INFO WHERE FISH_TYPE = F.FISH_TYPE) AS FISH_NAME, LENGTH
FROM FISH_INFO F
WHERE (FISH_TYPE, LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID ASC;